### ISSUE TITLE
App crash RNUserIdentityModule.java line 42 & line 44

### ISSUE THREAD

**Issue by tiggem1993** [juliandramirez/react-native-user-identity#15]
I am working in react native app, where I have implement this package. After implementing I did not get any error in development mode, but after app publish, Firebase Crashlytics showing me crashes on regular crashes.

Project currently running on:
React Native: 0.63
React:16.13.1

**Crashlytics log**

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { (has extras) }} to activity {com.rdiscovery/com.rdiscovery.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5200)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5241)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2230)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7824)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
```

**Caused By:**
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Promise.resolve(java.lang.Object)' on a null object reference
       at com.github.juliandramirez.rn.useridentity.RNUserIdentityModule$1.onActivityResult(RNUserIdentityModule.java:42)
       at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
       at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
       at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
       at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
       at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
       at android.app.Activity.dispatchActivityResult(Activity.java:8320)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5193)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5241)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2230)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7824)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
```

See screenshot for your reference:
![1](https://user-images.githubusercontent.com/16758184/120476644-70e71500-c3c8-11eb-9b5d-42c5a1f10006.png)
![2](https://user-images.githubusercontent.com/16758184/120476664-78a6b980-c3c8-11eb-9bf8-809017413217.png)

**See Crash Statistics:**
It shows total 19 devices are facing this crash after implementation.
Please note column named with "**Device Current**" is showing Android version.
![image (2)](https://user-images.githubusercontent.com/16758184/120477058-f23ea780-c3c8-11eb-9ed3-e88e0b43138b.png)

**Comment by tiggem1993** [comment]
@juliandramirez 
As per code review of RNUserIdentityModule.java, It seems like when user press "**OK**" or "**Cancel**" button then it occurred. 
I have recently also get crash on **line 83**. And line 83 shows when user selecting email from list is also get crashed. See screenshot. 
![3](https://user-images.githubusercontent.com/16758184/120766540-f5a47100-c537-11eb-93f8-9c7db7536014.png)

**Comment by tiggem1993** [comment]
@juliandramirez Is there any update?? Are you looking for this issue. If you need more details, please ask me.

**Comment by WouterFlorijn** [comment]
I'm also experiencing this error. Looking at the source code (although my Java knowledge is limited) it's clearly seems like a bug.

The `promise` member variable is only set in `triggerAccountSelection` on [line 54](https://github.com/juliandramirez/react-native-user-identity/blob/master/android/src/main/java/com/github/juliandramirez/rn/useridentity/RNUserIdentityModule.java#L54), but that method may not always be called before `onActivityResult`.

@juliandramirez I don't know what the intention of this code is, so I can't make a PR to fix it, but it seems fairly easy to fix. Would you have time to look into it?

Or @tiggem1993 did you manage to find a workaround?

**Comment by WouterFlorijn** [comment]
@juliandramirez @tiggem1993 Based on [this example](https://archive.reactnative.dev/docs/native-modules-android#getting-activity-result-from-startactivityforresult) in React Native's own docs, I created PR #24 that should fix this issue. Could this be reviewed/merged/released?

**Comment by juliandramirez** [comment]
done @WouterFlorijn ! let me know how it goes

**Comment by WouterFlorijn** [comment]
@juliandramirez great, I'll let you know once we've released this if any error is still showing.

**Comment by WouterFlorijn** [comment]
@juliandramirez looks like this fixed the issue! We haven't seen any alerts since the last app release (3 days ago) whereas before it would show up at least 20 times per day.

**Comment by juliandramirez** [comment]
very happy to hear and thank you very much for taking the time to fix this @WouterFlorijn
