### ISSUE TITLE
 App is crashing on click of Cancel button in Android Platform

### ISSUE THREAD

**Issue by LudinaReema** [juliandramirez/react-native-user-identity#37]
Code: 

try {
      const result = await RNUserIdentity.getUserId({
        iosUserConfirmation: false,
      });
      if (result === null) {
        alert('User canceled UI flow');
      } 
      else {
        handleEmail(result);
      }
} 
catch (error) {
      console.log('error');
}

**Comment by juliandramirez** [comment]
add android logs/exception details here

**Comment by LudinaReema** [comment]
**React-native version**: 0.69.4

**Logcat logs**:

2023-06-05 11:54:02.117 371-428/? E/android.hardware.audio@7.0-impl.ranchu: device/generic/goldfish/audio/stream_out.cpp:updateSourceMetadata:378 failure: Result::NOT_SUPPORTED
2023-06-05 11:54:02.118 385-457/? D/goldfish-address-space: claimShared: Ask to claim region [0x1ec62c000 0x1ecc58000]
2023-06-05 11:54:02.127 9326-9326/in.test E/RNDocumentPicker: promise was null in onActivityResult
2023-06-05 11:54:02.128 9326-9326/in.test D/AndroidRuntime: Shutting down VM

--------- beginning of crash
2023-06-05 11:54:02.129 9326-9326/in.test E/AndroidRuntime: FATAL EXCEPTION: main
Process: in.test, PID: 9326
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} to activity {in.test/in.test.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
at android.app.ActivityThread.deliverResults(ActivityThread.java:5347)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386)
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
at in.test.LeegalityModule.onActivityResult(LeegalityModule.java:54)
at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:339)
at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:824)
at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:133)
at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:70)
at in.test.MainActivity.onActivityResult(MainActivity.java:48)
at android.app.Activity.dispatchActivityResult(Activity.java:8613)
at android.app.ActivityThread.deliverResults(ActivityThread.java:5340)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5386) 
at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67) 
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at android.app.ActivityThread.main(ActivityThread.java:7898) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
2023-06-05 11:54:02.130 9326-9419/in.test I/ReactNativeJS: 'result', null
2023-06-05 11:54:02.133 386-440/? W/RanchuHwc: presentDisplay display has no layers to compose, flushing client target buffer.
2023-06-05 11:54:02.147 386-440/? W/RanchuHwc: presentDisplay display has no layers to compose, flushing client target buffer.
2023-06-05 11:54:02.149 874-944/com.android.systemui D/EGL_emulation: app_time_stats: avg=2101.39ms min=2101.39ms max=2101.39ms count=1
2023-06-05 11:54:02.164 386-440/? W/RanchuHwc: presentDisplay display has no layers to compose, flushing client target buffer.
2023-06-05 11:54:02.173 9326-9352/in.test D/libcrashlytics: Initializing libcrashlytics version 3.2.0
2023-06-05 11:54:02.174 9326-9352/in.test D/libcrashlytics: Initializing native crash handling successful.


**Screenshot attached FYR:**
<img width="1065" alt="Screenshot 2023-06-05 at 11 48 06 AM" src="https://github.com/juliandramirez/react-native-user-identity/assets/47420463/cfc09585-df23-4729-b790-e731963dbccc">

**Comment by LudinaReema** [comment]
@juliandramirez Any update on this issue?

**Comment by Vigneshwaran-crypto** [comment]
If anyone fixed this Please update
